### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by ThunderPaul** [ralfhergert/pc2-telemetry#1]
Hello,
I'm developing a small java application to read the project cars 2 UDP from the PS4.

First of all I wanted to thank you because reading your code I'm understanding many things (I've never worked with UDP).

I have a question to ask you, using the data transmission mode ProjectCars2, I managed to read some data, such as the temperature of the brakes and the tires, but the bytes relative to the front left tire, I always get to zero, the other 3 tires they arrive with their correct value.

Did it happen to you, by any chance?

**Comment by ralfhergert** [comment]
Hi ThunderPaul,
Thank you for having a look at this project. I'm happy if it helped you to shed some light onto Java and UDP.

For your question: Yes, I observed the same issue with the data for the front left tyre. And there is a multitude of other wrong values too. See this forum post started on 6. of November 2017 http://forum.projectcarsgame.com/showthread.php?56963-PCARS2-UDP-API-Bug-reports
It states that especially for the front left tyre the values for temperature, airPressure, brakeTemp, tyreWear and suspensionRideHeight are either fixed values (they never change) or appear to be random. Also the terrain-flags for the front left tyre is broken.
In the same forum thread on 16. Feb 2018 Martin Moravec wrote, that they are going to sort these values in a next patch. So my hopes are high, that we get a fully working UDP API soon.

**Comment by ThunderPaul** [comment]
Thank you very much for your reply, we hope the patch will arrive soon.
